/*
Taxonomy API

Use the Taxonomy API to discover the most appropriate eBay categories under which sellers can offer inventory items for sale, and the most likely categories under which buyers can browse or search for items to purchase. In addition, the Taxonomy API provides metadata about the required and recommended category aspects to include in listings, and also has two operations to retrieve parts compatibility information.

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taxonomy

import (
	"encoding/json"
)

// BaseCategoryTree This type contains identifying information for the category tree associated with a particular eBay marketplace.
type BaseCategoryTree struct {
	// The unique identifier of the eBay category tree for the specified marketplace.
	CategoryTreeId *string `json:"categoryTreeId,omitempty"`
	// The version of the category tree identified by categoryTreeId. It's a good idea to cache this value for comparison so you can determine if this category tree has been modified in subsequent calls.
	CategoryTreeVersion *string `json:"categoryTreeVersion,omitempty"`
}

// NewBaseCategoryTree instantiates a new BaseCategoryTree object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseCategoryTree() *BaseCategoryTree {
	this := BaseCategoryTree{}
	return &this
}

// NewBaseCategoryTreeWithDefaults instantiates a new BaseCategoryTree object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseCategoryTreeWithDefaults() *BaseCategoryTree {
	this := BaseCategoryTree{}
	return &this
}

// GetCategoryTreeId returns the CategoryTreeId field value if set, zero value otherwise.
func (o *BaseCategoryTree) GetCategoryTreeId() string {
	if o == nil || o.CategoryTreeId == nil {
		var ret string
		return ret
	}
	return *o.CategoryTreeId
}

// GetCategoryTreeIdOk returns a tuple with the CategoryTreeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseCategoryTree) GetCategoryTreeIdOk() (*string, bool) {
	if o == nil || o.CategoryTreeId == nil {
		return nil, false
	}
	return o.CategoryTreeId, true
}

// HasCategoryTreeId returns a boolean if a field has been set.
func (o *BaseCategoryTree) HasCategoryTreeId() bool {
	if o != nil && o.CategoryTreeId != nil {
		return true
	}

	return false
}

// SetCategoryTreeId gets a reference to the given string and assigns it to the CategoryTreeId field.
func (o *BaseCategoryTree) SetCategoryTreeId(v string) {
	o.CategoryTreeId = &v
}

// GetCategoryTreeVersion returns the CategoryTreeVersion field value if set, zero value otherwise.
func (o *BaseCategoryTree) GetCategoryTreeVersion() string {
	if o == nil || o.CategoryTreeVersion == nil {
		var ret string
		return ret
	}
	return *o.CategoryTreeVersion
}

// GetCategoryTreeVersionOk returns a tuple with the CategoryTreeVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseCategoryTree) GetCategoryTreeVersionOk() (*string, bool) {
	if o == nil || o.CategoryTreeVersion == nil {
		return nil, false
	}
	return o.CategoryTreeVersion, true
}

// HasCategoryTreeVersion returns a boolean if a field has been set.
func (o *BaseCategoryTree) HasCategoryTreeVersion() bool {
	if o != nil && o.CategoryTreeVersion != nil {
		return true
	}

	return false
}

// SetCategoryTreeVersion gets a reference to the given string and assigns it to the CategoryTreeVersion field.
func (o *BaseCategoryTree) SetCategoryTreeVersion(v string) {
	o.CategoryTreeVersion = &v
}

func (o BaseCategoryTree) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CategoryTreeId != nil {
		toSerialize["categoryTreeId"] = o.CategoryTreeId
	}
	if o.CategoryTreeVersion != nil {
		toSerialize["categoryTreeVersion"] = o.CategoryTreeVersion
	}
	return json.Marshal(toSerialize)
}

type NullableBaseCategoryTree struct {
	value *BaseCategoryTree
	isSet bool
}

func (v NullableBaseCategoryTree) Get() *BaseCategoryTree {
	return v.value
}

func (v *NullableBaseCategoryTree) Set(val *BaseCategoryTree) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseCategoryTree) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseCategoryTree) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseCategoryTree(val *BaseCategoryTree) *NullableBaseCategoryTree {
	return &NullableBaseCategoryTree{value: val, isSet: true}
}

func (v NullableBaseCategoryTree) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseCategoryTree) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


