/*
Feed API

<p>The <strong>Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>

API version: v1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feed

import (
	"encoding/json"
)

// OrderFilterCriteria The type that defines the fields for the order filters.
type OrderFilterCriteria struct {
	CreationDateRange *DateRange `json:"creationDateRange,omitempty"`
	ModifiedDateRange *DateRange `json:"modifiedDateRange,omitempty"`
	// The order status of the orders returned. If the filter is omitted from createOrderTask call, orders that are in both ACTIVE and COMPLETED states are returned. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/feed/types/api:OrderStatusEnum'>eBay API documentation</a>
	OrderStatus *string `json:"orderStatus,omitempty"`
}

// NewOrderFilterCriteria instantiates a new OrderFilterCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderFilterCriteria() *OrderFilterCriteria {
	this := OrderFilterCriteria{}
	return &this
}

// NewOrderFilterCriteriaWithDefaults instantiates a new OrderFilterCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderFilterCriteriaWithDefaults() *OrderFilterCriteria {
	this := OrderFilterCriteria{}
	return &this
}

// GetCreationDateRange returns the CreationDateRange field value if set, zero value otherwise.
func (o *OrderFilterCriteria) GetCreationDateRange() DateRange {
	if o == nil || o.CreationDateRange == nil {
		var ret DateRange
		return ret
	}
	return *o.CreationDateRange
}

// GetCreationDateRangeOk returns a tuple with the CreationDateRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFilterCriteria) GetCreationDateRangeOk() (*DateRange, bool) {
	if o == nil || o.CreationDateRange == nil {
		return nil, false
	}
	return o.CreationDateRange, true
}

// HasCreationDateRange returns a boolean if a field has been set.
func (o *OrderFilterCriteria) HasCreationDateRange() bool {
	if o != nil && o.CreationDateRange != nil {
		return true
	}

	return false
}

// SetCreationDateRange gets a reference to the given DateRange and assigns it to the CreationDateRange field.
func (o *OrderFilterCriteria) SetCreationDateRange(v DateRange) {
	o.CreationDateRange = &v
}

// GetModifiedDateRange returns the ModifiedDateRange field value if set, zero value otherwise.
func (o *OrderFilterCriteria) GetModifiedDateRange() DateRange {
	if o == nil || o.ModifiedDateRange == nil {
		var ret DateRange
		return ret
	}
	return *o.ModifiedDateRange
}

// GetModifiedDateRangeOk returns a tuple with the ModifiedDateRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFilterCriteria) GetModifiedDateRangeOk() (*DateRange, bool) {
	if o == nil || o.ModifiedDateRange == nil {
		return nil, false
	}
	return o.ModifiedDateRange, true
}

// HasModifiedDateRange returns a boolean if a field has been set.
func (o *OrderFilterCriteria) HasModifiedDateRange() bool {
	if o != nil && o.ModifiedDateRange != nil {
		return true
	}

	return false
}

// SetModifiedDateRange gets a reference to the given DateRange and assigns it to the ModifiedDateRange field.
func (o *OrderFilterCriteria) SetModifiedDateRange(v DateRange) {
	o.ModifiedDateRange = &v
}

// GetOrderStatus returns the OrderStatus field value if set, zero value otherwise.
func (o *OrderFilterCriteria) GetOrderStatus() string {
	if o == nil || o.OrderStatus == nil {
		var ret string
		return ret
	}
	return *o.OrderStatus
}

// GetOrderStatusOk returns a tuple with the OrderStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFilterCriteria) GetOrderStatusOk() (*string, bool) {
	if o == nil || o.OrderStatus == nil {
		return nil, false
	}
	return o.OrderStatus, true
}

// HasOrderStatus returns a boolean if a field has been set.
func (o *OrderFilterCriteria) HasOrderStatus() bool {
	if o != nil && o.OrderStatus != nil {
		return true
	}

	return false
}

// SetOrderStatus gets a reference to the given string and assigns it to the OrderStatus field.
func (o *OrderFilterCriteria) SetOrderStatus(v string) {
	o.OrderStatus = &v
}

func (o OrderFilterCriteria) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreationDateRange != nil {
		toSerialize["creationDateRange"] = o.CreationDateRange
	}
	if o.ModifiedDateRange != nil {
		toSerialize["modifiedDateRange"] = o.ModifiedDateRange
	}
	if o.OrderStatus != nil {
		toSerialize["orderStatus"] = o.OrderStatus
	}
	return json.Marshal(toSerialize)
}

type NullableOrderFilterCriteria struct {
	value *OrderFilterCriteria
	isSet bool
}

func (v NullableOrderFilterCriteria) Get() *OrderFilterCriteria {
	return v.value
}

func (v *NullableOrderFilterCriteria) Set(val *OrderFilterCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderFilterCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderFilterCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderFilterCriteria(val *OrderFilterCriteria) *NullableOrderFilterCriteria {
	return &NullableOrderFilterCriteria{value: val, isSet: true}
}

func (v NullableOrderFilterCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderFilterCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


