/*
Feed API

<p>The <strong>Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>

API version: v1.3.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feed

import (
	"encoding/json"
)

// CreateServiceMetricsTaskRequest The type that defines the fields for the Customer Service Metric reports generated with the Feed API.
type CreateServiceMetricsTaskRequest struct {
	// The feedType specified for the task. The report lists the transaction details that contribute to the service metrics evaluation. Supported types include: CUSTOMER_SERVICE_METRICS_REPORT
	FeedType *string `json:"feedType,omitempty"`
	FilterCriteria *CustomerServiceMetricsFilterCriteria `json:"filterCriteria,omitempty"`
	// The version number of the file format. Valid value: 1.0
	SchemaVersion *string `json:"schemaVersion,omitempty"`
}

// NewCreateServiceMetricsTaskRequest instantiates a new CreateServiceMetricsTaskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateServiceMetricsTaskRequest() *CreateServiceMetricsTaskRequest {
	this := CreateServiceMetricsTaskRequest{}
	return &this
}

// NewCreateServiceMetricsTaskRequestWithDefaults instantiates a new CreateServiceMetricsTaskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateServiceMetricsTaskRequestWithDefaults() *CreateServiceMetricsTaskRequest {
	this := CreateServiceMetricsTaskRequest{}
	return &this
}

// GetFeedType returns the FeedType field value if set, zero value otherwise.
func (o *CreateServiceMetricsTaskRequest) GetFeedType() string {
	if o == nil || o.FeedType == nil {
		var ret string
		return ret
	}
	return *o.FeedType
}

// GetFeedTypeOk returns a tuple with the FeedType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServiceMetricsTaskRequest) GetFeedTypeOk() (*string, bool) {
	if o == nil || o.FeedType == nil {
		return nil, false
	}
	return o.FeedType, true
}

// HasFeedType returns a boolean if a field has been set.
func (o *CreateServiceMetricsTaskRequest) HasFeedType() bool {
	if o != nil && o.FeedType != nil {
		return true
	}

	return false
}

// SetFeedType gets a reference to the given string and assigns it to the FeedType field.
func (o *CreateServiceMetricsTaskRequest) SetFeedType(v string) {
	o.FeedType = &v
}

// GetFilterCriteria returns the FilterCriteria field value if set, zero value otherwise.
func (o *CreateServiceMetricsTaskRequest) GetFilterCriteria() CustomerServiceMetricsFilterCriteria {
	if o == nil || o.FilterCriteria == nil {
		var ret CustomerServiceMetricsFilterCriteria
		return ret
	}
	return *o.FilterCriteria
}

// GetFilterCriteriaOk returns a tuple with the FilterCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServiceMetricsTaskRequest) GetFilterCriteriaOk() (*CustomerServiceMetricsFilterCriteria, bool) {
	if o == nil || o.FilterCriteria == nil {
		return nil, false
	}
	return o.FilterCriteria, true
}

// HasFilterCriteria returns a boolean if a field has been set.
func (o *CreateServiceMetricsTaskRequest) HasFilterCriteria() bool {
	if o != nil && o.FilterCriteria != nil {
		return true
	}

	return false
}

// SetFilterCriteria gets a reference to the given CustomerServiceMetricsFilterCriteria and assigns it to the FilterCriteria field.
func (o *CreateServiceMetricsTaskRequest) SetFilterCriteria(v CustomerServiceMetricsFilterCriteria) {
	o.FilterCriteria = &v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *CreateServiceMetricsTaskRequest) GetSchemaVersion() string {
	if o == nil || o.SchemaVersion == nil {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServiceMetricsTaskRequest) GetSchemaVersionOk() (*string, bool) {
	if o == nil || o.SchemaVersion == nil {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *CreateServiceMetricsTaskRequest) HasSchemaVersion() bool {
	if o != nil && o.SchemaVersion != nil {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *CreateServiceMetricsTaskRequest) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

func (o CreateServiceMetricsTaskRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FeedType != nil {
		toSerialize["feedType"] = o.FeedType
	}
	if o.FilterCriteria != nil {
		toSerialize["filterCriteria"] = o.FilterCriteria
	}
	if o.SchemaVersion != nil {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	return json.Marshal(toSerialize)
}

type NullableCreateServiceMetricsTaskRequest struct {
	value *CreateServiceMetricsTaskRequest
	isSet bool
}

func (v NullableCreateServiceMetricsTaskRequest) Get() *CreateServiceMetricsTaskRequest {
	return v.value
}

func (v *NullableCreateServiceMetricsTaskRequest) Set(val *CreateServiceMetricsTaskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateServiceMetricsTaskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateServiceMetricsTaskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateServiceMetricsTaskRequest(val *CreateServiceMetricsTaskRequest) *NullableCreateServiceMetricsTaskRequest {
	return &NullableCreateServiceMetricsTaskRequest{value: val, isSet: true}
}

func (v NullableCreateServiceMetricsTaskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateServiceMetricsTaskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


