/*
Account API

The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (seller-defined custom policies and eBay business policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#requirements\">Account API requirements and restrictions</a>.

API version: v1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package account

import (
	"encoding/json"
)

// PaymentsProgramOnboardingSteps The payments program onboarding steps, status, and link.
type PaymentsProgramOnboardingSteps struct {
	// The name of the step in the steps array. Over time, these names are subject to change as processes change. The output sample contains example step names. Review an actual call response for updated step names. 
	Name *string `json:"name,omitempty"`
	// This enumeration value indicates the status of the associated step. <p> <span class=\"tablenote\"><strong>Note:</strong> Only one step can be <code>IN_PROGRESS</code> at a time.</span></p> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:PaymentsProgramOnboardingStepStatus'>eBay API documentation</a>
	Status *string `json:"status,omitempty"`
	// This URL provides access to the <code>IN_PROGRESS</code> step.
	WebUrl *string `json:"webUrl,omitempty"`
}

// NewPaymentsProgramOnboardingSteps instantiates a new PaymentsProgramOnboardingSteps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentsProgramOnboardingSteps() *PaymentsProgramOnboardingSteps {
	this := PaymentsProgramOnboardingSteps{}
	return &this
}

// NewPaymentsProgramOnboardingStepsWithDefaults instantiates a new PaymentsProgramOnboardingSteps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentsProgramOnboardingStepsWithDefaults() *PaymentsProgramOnboardingSteps {
	this := PaymentsProgramOnboardingSteps{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PaymentsProgramOnboardingSteps) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentsProgramOnboardingSteps) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PaymentsProgramOnboardingSteps) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PaymentsProgramOnboardingSteps) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PaymentsProgramOnboardingSteps) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentsProgramOnboardingSteps) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PaymentsProgramOnboardingSteps) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PaymentsProgramOnboardingSteps) SetStatus(v string) {
	o.Status = &v
}

// GetWebUrl returns the WebUrl field value if set, zero value otherwise.
func (o *PaymentsProgramOnboardingSteps) GetWebUrl() string {
	if o == nil || o.WebUrl == nil {
		var ret string
		return ret
	}
	return *o.WebUrl
}

// GetWebUrlOk returns a tuple with the WebUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentsProgramOnboardingSteps) GetWebUrlOk() (*string, bool) {
	if o == nil || o.WebUrl == nil {
		return nil, false
	}
	return o.WebUrl, true
}

// HasWebUrl returns a boolean if a field has been set.
func (o *PaymentsProgramOnboardingSteps) HasWebUrl() bool {
	if o != nil && o.WebUrl != nil {
		return true
	}

	return false
}

// SetWebUrl gets a reference to the given string and assigns it to the WebUrl field.
func (o *PaymentsProgramOnboardingSteps) SetWebUrl(v string) {
	o.WebUrl = &v
}

func (o PaymentsProgramOnboardingSteps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.WebUrl != nil {
		toSerialize["webUrl"] = o.WebUrl
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentsProgramOnboardingSteps struct {
	value *PaymentsProgramOnboardingSteps
	isSet bool
}

func (v NullablePaymentsProgramOnboardingSteps) Get() *PaymentsProgramOnboardingSteps {
	return v.value
}

func (v *NullablePaymentsProgramOnboardingSteps) Set(val *PaymentsProgramOnboardingSteps) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentsProgramOnboardingSteps) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentsProgramOnboardingSteps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentsProgramOnboardingSteps(val *PaymentsProgramOnboardingSteps) *NullablePaymentsProgramOnboardingSteps {
	return &NullablePaymentsProgramOnboardingSteps{value: val, isSet: true}
}

func (v NullablePaymentsProgramOnboardingSteps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentsProgramOnboardingSteps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


