/*
Account API

The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (seller-defined custom policies and eBay business policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#requirements\">Account API requirements and restrictions</a>.

API version: v1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package account

import (
	"encoding/json"
)

// CustomPolicyResponse struct for CustomPolicyResponse
type CustomPolicyResponse struct {
	// This array contains the custom policies that match the input criteria.
	CustomPolicies *[]CompactCustomPolicyResponse `json:"customPolicies,omitempty"`
	// <i>This field is for future use.</i>
	Href *string `json:"href,omitempty"`
	// <i>This field is for future use.</i>
	Limit *int32 `json:"limit,omitempty"`
	// <i>This field is for future use.</i>
	Next *string `json:"next,omitempty"`
	// <i>This field is for future use.</i>
	Offset *int32 `json:"offset,omitempty"`
	// <i>This field is for future use.</i>
	Prev *string `json:"prev,omitempty"`
	// <i>This field is for future use.</i>
	Total *int32 `json:"total,omitempty"`
}

// NewCustomPolicyResponse instantiates a new CustomPolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomPolicyResponse() *CustomPolicyResponse {
	this := CustomPolicyResponse{}
	return &this
}

// NewCustomPolicyResponseWithDefaults instantiates a new CustomPolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomPolicyResponseWithDefaults() *CustomPolicyResponse {
	this := CustomPolicyResponse{}
	return &this
}

// GetCustomPolicies returns the CustomPolicies field value if set, zero value otherwise.
func (o *CustomPolicyResponse) GetCustomPolicies() []CompactCustomPolicyResponse {
	if o == nil || o.CustomPolicies == nil {
		var ret []CompactCustomPolicyResponse
		return ret
	}
	return *o.CustomPolicies
}

// GetCustomPoliciesOk returns a tuple with the CustomPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPolicyResponse) GetCustomPoliciesOk() (*[]CompactCustomPolicyResponse, bool) {
	if o == nil || o.CustomPolicies == nil {
		return nil, false
	}
	return o.CustomPolicies, true
}

// HasCustomPolicies returns a boolean if a field has been set.
func (o *CustomPolicyResponse) HasCustomPolicies() bool {
	if o != nil && o.CustomPolicies != nil {
		return true
	}

	return false
}

// SetCustomPolicies gets a reference to the given []CompactCustomPolicyResponse and assigns it to the CustomPolicies field.
func (o *CustomPolicyResponse) SetCustomPolicies(v []CompactCustomPolicyResponse) {
	o.CustomPolicies = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *CustomPolicyResponse) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPolicyResponse) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *CustomPolicyResponse) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *CustomPolicyResponse) SetHref(v string) {
	o.Href = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *CustomPolicyResponse) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPolicyResponse) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *CustomPolicyResponse) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *CustomPolicyResponse) SetLimit(v int32) {
	o.Limit = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *CustomPolicyResponse) GetNext() string {
	if o == nil || o.Next == nil {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPolicyResponse) GetNextOk() (*string, bool) {
	if o == nil || o.Next == nil {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *CustomPolicyResponse) HasNext() bool {
	if o != nil && o.Next != nil {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *CustomPolicyResponse) SetNext(v string) {
	o.Next = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *CustomPolicyResponse) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPolicyResponse) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *CustomPolicyResponse) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *CustomPolicyResponse) SetOffset(v int32) {
	o.Offset = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *CustomPolicyResponse) GetPrev() string {
	if o == nil || o.Prev == nil {
		var ret string
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPolicyResponse) GetPrevOk() (*string, bool) {
	if o == nil || o.Prev == nil {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *CustomPolicyResponse) HasPrev() bool {
	if o != nil && o.Prev != nil {
		return true
	}

	return false
}

// SetPrev gets a reference to the given string and assigns it to the Prev field.
func (o *CustomPolicyResponse) SetPrev(v string) {
	o.Prev = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *CustomPolicyResponse) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPolicyResponse) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *CustomPolicyResponse) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *CustomPolicyResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o CustomPolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CustomPolicies != nil {
		toSerialize["customPolicies"] = o.CustomPolicies
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	if o.Next != nil {
		toSerialize["next"] = o.Next
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	if o.Prev != nil {
		toSerialize["prev"] = o.Prev
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableCustomPolicyResponse struct {
	value *CustomPolicyResponse
	isSet bool
}

func (v NullableCustomPolicyResponse) Get() *CustomPolicyResponse {
	return v.value
}

func (v *NullableCustomPolicyResponse) Set(val *CustomPolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomPolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomPolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomPolicyResponse(val *CustomPolicyResponse) *NullableCustomPolicyResponse {
	return &NullableCustomPolicyResponse{value: val, isSet: true}
}

func (v NullableCustomPolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomPolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


